# Generated by Django 2.0.1 on 2018-10-12 21:30

from django_servi.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
